server.port=0
spring.application.name=api-gateway
eureka.client.service-url.defaultZone=http://localhost:8764/eureka
logging.level.root=INFO
logging.level.org.springframework.cloud.gateway=TRACE
logging.level.org.springframework.cloud.gateway.route.RouteDefinitionLocator=INFO


#inventory
spring.cloud.gateway.server.webflux.routes[0].id=inventory-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://inventory-service
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/inventory/**